### ISSUE TITLE
USER STORY:  Prompts to Sign In or Sign Up for Interaction

### ISSUE THREAD

**Issue by Mustafa-Vienna** [Mustafa-Vienna/PetAdoption#19]
As a **visitor**, I want to **see prompts to sign in or sign up to interact with the post** so that **I know that I need an account to like or comment on the post.**

#### Acceptance Criteria
- The navigation bar displays "Sign In" and "Sign Up" links if the user is not logged in.
- A "Sign In to Like" prompt appears next to the like button, indicating that sign-in is required to like the post.
- In the "Leave Your Comment" section, a message with "Sign In" and "Sign Up" links informs visitors that registration is required to comment.

#### Tasks
- [x] Display "Sign In" and "Sign Up" links in the navigation bar if the user is not logged in.
- [x] Add "Sign In to Like" prompt near the like button for visitors.
- [x] In the "Leave Your Comment" section, show a message with "Sign In" and "Sign Up" links to encourage visitors to log in.
