### ISSUE TITLE
USER STORY:  View and Interact with Post as a Logged-In User

### ISSUE THREAD

**Issue by Mustafa-Vienna** [Mustafa-Vienna/PetAdoption#22]
As a **logged-in user**, I want to **like the post and see an updated like count and message** so that **I know how many others liked the post and see my interaction.**

#### Acceptance Criteria
- The like button displays as a gray heart icon if the user hasn’t liked the post.
- Clicking the gray heart icon changes it to a red heart and updates the like count and message.
- The like count displays as follows:
  - If no one has liked the post: "0 users like this post."
  - If the user is the first to like: "1 - You like this post."
  - If the user and one other person have liked: "2 - You and 1 other user like this post."
  - If the user and multiple others have liked: "You and X other users like this post."
  - If only one other user has liked: "1 user likes this post."
  - If multiple users (not including the logged-in user) have liked: "X users like this post."

#### Tasks
- [x] Display the gray heart icon if the user hasn’t liked the post.
- [x] Change the heart icon to red and update the like count when clicked.
- [x] Implement logic for each like count display scenario as described.
